---
# tasks file for roles/backend
- name: Create backend container and connect to network
  community.docker.docker_container:
    name: backend
    image: "robinarnoux/backend:latest"
    networks:
      - name: "app-network"
    ports:
      - 8080:80
    env:
      POSTGRES_USER: "{{ psql_user }}"
      POSTGRES_PASSWORD: "{{ psql_password }}"
      POSTGRES_DB: "{{ psql_db }}"