---
# tasks file for roles/front
# tasks file for roles/backend
- name: Create front container and connect to network
  community.docker.docker_container:
    name: front
    image: "robinarnoux/front:latest"
    networks:
      - name: "app-network"