---
# tasks file for roles/httpd
- name: Create httpd container and connect to network
  community.docker.docker_container:
    name: httpd
    image: "robinarnoux/httpd:latest"
    networks:
      - name: "app-network"
    auto_remove: true