name: build and build-and-push-docker-image
on:
  workflow_run:
    branches: [main]
    workflows: ["test-backend"]
    types:
      - completed
    

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./TP-Part01/Backend/    # relative path to the place where source code with Dockerfile is located
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend # Note: tags has to be all lower-case
          push: true # Build and push only on the main branch
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./TP-Part01/Database/psql # relative path to the place where source code with Dockerfile is located
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/database  # Note: tags has to be all lower-case
          push: true # Build and push only on the main branch
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./TP-Part01/HttpServer   # relative path to the place where source code with Dockerfile is located
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/httpd   # Note: tags has to be all lower-case
          push: true # Build and push only on the main branch
