name: build and push back

on:
  workflow_run:
    branches: [main]
    workflows: ["test-backend"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./TP-Part01/Backend/    # relative path to the place where source code with Dockerfile is located
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend # Note: tags has to be all lower-case
          push: true # Build and push only on the main branch
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "First workflow was a failure"
